language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - all_languages="python,shell"
install: make deps
script: make test
branches:
    only:
        - master
