language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y ruby
install: make deps
script: make test
branches:
    only:
        - master
